// Prevents additional console window on Windows in release
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Bring all modules directly into this bin crate so the #[macro_export] helper
// macros generated by #[tauri::command] are visible to tauri::generate_handler!
// in the same crate.
mod browser;
mod boot_helpers;
mod anime;
mod kazumi;
mod xpath_lite;
mod app_logger;
mod cache;
mod commands;
mod config;
mod download_engine;
mod downloader;
mod extractor;
mod game_scrape;
mod gx;
mod game_translator;
mod licensing;
mod paths;
mod books;
mod search_engine;
mod snapshot;
mod system_monitor;
mod trainer;
mod translator;
mod updater;

use tauri::{Emitter, Manager};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::menu::{Menu, MenuItem};
use tauri::WindowEvent;
use std::sync::atomic::{AtomicBool, Ordering};

/// 全局开关: 关闭窗口时最小化到托盘 (后台静默下载)
/// 在 setup 中根据 config.background_download 初始化
static BACKGROUND_DOWNLOAD: AtomicBool = AtomicBool::new(true);

use crate::anime::{
    anime_home, anime_detail, anime_search_bgm,
    anime_follow, anime_follow_toggle, anime_follow_progress, anime_danmaku,
    anime_sources, anime_search_online, anime_search_all, anime_episodes, anime_resolve,
    anime_hot, anime_rec_paged,
};

use crate::commands::{
    vx_window_min, vx_window_toggle_max, vx_window_close,
    AppState,
    get_config, save_config,
    show_main_window,
    license_status, license_activate,
    browse, browse_by_category, get_adult_tags, browse_adult, search_adult, adult_browse_local, adult_categories, adult_total, search, fetch_detail, fetch_downloads,
    translate, translate_game_info, set_translate_lang, get_translate_lang, clear_translate_cache, translate_force,
    game_tr_set_engine, game_tr_get_engine, game_tr_set_config, game_tr_get_config,
    game_tr_translate, game_tr_translate_batch, game_tr_translate_dir, game_tr_clear_cache,
    save_translated_name, save_translated_names, translate_all_game_names,
    start_download, cancel_download, pause_download, resume_download, retry_download, get_downloads_status,
    parse_torrent_preview,
    get_speed_engine_status, aria2_status, aria2_start, aria2_stop, aria2_get_active_downloads,
    clear_cache, snapshot_stats, snapshot_categories, refresh_snapshot, preload_byko, clear_snapshot, reset_adult_tags, recommend,
    get_cache_usage, clear_temp_cache, clear_app_cache,
    open_folder, open_file, delete_path, launch_program, program_exists, extract_archive, list_archives, check_bt_disk_progress, browse_path, get_game_translator_path,
    copy_to_clipboard,
    get_app_info, mark_version_seen, check_app_update, download_app_update,
    get_system_status, append_frontend_log,
    open_external_browser,
    create_desktop_shortcut, list_exe_candidates,
    repair_runtime,
    restart_system,
    game_scrape_site, game_scrape_pick_download,
    gx_sync, gx_status, gx_tags, gx_browse, gx_detail, gx_resources, gx_pick_download, gx_related,
    open_player_window, player_take_payload, focus_main_and_open, raise_main_window, main_sync_subject,
};



use crate::books::{
    book_home, book_search, book_content, book_download, book_extra_downloads,
    book_local_dir, book_open_local_dir, book_import, book_probe, book_translate,
};

use crate::trainer::{
    tr_sync, tr_index, tr_detail, tr_download, tr_library,
    tr_import, tr_delete, tr_launch, tr_rename, tr_translate_names, tr_open_folder,
    tr_defender_exclude,
};


/// ★ 在 Windows 子系统应用中将 stderr 重定向到日志文件
///   原因: windows_subsystem="windows" 的程序没有控制台句柄,
///   直接运行时 eprintln! 输出会丢失; 若用 cmd /c 重定向又会弹出 CMD 窗口.
///   解决方案: 在 main() 最开头用 SetStdHandle 把 stderr 指向日志文件,
///   这样无需 shell 重定向, 双击 exe 即可静默运行并捕获诊断日志.
#[cfg(windows)]
fn redirect_stderr_to_log() {
    use std::fs::OpenOptions;
    use std::os::windows::io::AsRawHandle;
    use windows_sys::Win32::System::Console::SetStdHandle;
    use windows_sys::Win32::System::Console::STD_ERROR_HANDLE;

    // 日志目录: 可执行文件同级的 logs/
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    let logs_dir = exe_dir.join("logs");
    let _ = std::fs::create_dir_all(&logs_dir);

    // 用追加模式打开 stderr.log (每次启动追加, 不覆盖)
    // ★ 完整保留全部日志 (2026-09-15): 不再做轮转, 方便排查历史 bug
    let log_path = logs_dir.join("stderr.log");
    if let Ok(file) = OpenOptions::new().create(true).append(true).open(&log_path) {
        let handle = file.as_raw_handle();
        // SetStdHandle(STD_ERROR_HANDLE, handle) 替换进程的 stderr 句柄
        // 之后所有 eprintln! / eprint! 都会写入该文件
        unsafe {
            SetStdHandle(STD_ERROR_HANDLE, handle as *mut _);
        }
        // 让 file 保持打开 (leak), 确保句柄在进程生命周期内有效
        std::mem::forget(file);
    }
}

#[cfg(not(windows))]
fn redirect_stderr_to_log() {}

/// 获取系统总内存 (MB)
/// ★ 修复 (2026-09-28): sysinfo 0.30 起内存单位是「字节」, 旧实现只 /1024 得到的是 KB
///   (system.log 里 memory_mb=33384912 实际是 32GB 的 KB 值), 这里补第二级 /1024 得到真正的 MB。
fn get_system_memory_mb() -> u64 {
    use sysinfo::System;
    let mut sys = System::new();
    sys.refresh_memory();
    sys.total_memory() / 1024 / 1024
}

/// 获取本进程 RSS 常驻内存 (MB)
/// ★ 新增 (2026-09-28): 用于验证「下载时下载器内存 < 150MB」的目标。
///   sysinfo 0.30 的 Process::memory() 返回字节, 取当前进程的常驻集大小 (RSS)。
fn get_app_rss_mb() -> u64 {
    use sysinfo::System;
    let mut sys = System::new();
    if let Ok(pid) = sysinfo::get_current_pid() {
        sys.refresh_process(pid);
        if let Some(p) = sys.process(pid) {
            return p.memory() / 1024 / 1024;
        }
    }
    0
}

/// 获取 CPU 核心数
fn num_cpus() -> usize {
    std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1)
}

fn main() {
    // ★ 第一步: 重定向 stderr 到 logs/stderr.log (必须在所有 eprintln! 之前)
    redirect_stderr_to_log();

    // ★ CPU/内存优化 (2026-09-28): 下载引擎限定 2 核 4 线程 (VORTEX_WORKER_THREADS 可覆盖)
    //   把自定义 tokio 运行时注入 Tauri (async_runtime::set), 所有下载任务跑在 4 个 worker 上;
    //   blocking 池上限收紧到 8, 避免 spawn_blocking 撑出大量线程栈 → 显著降内存.
    //   Tauri 只持有 Handle, Runtime 需常驻 → forget 保活至进程结束.
    let worker_threads = std::env::var("VORTEX_WORKER_THREADS")
        .ok()
        .and_then(|v| v.parse::<usize>().ok())
        .unwrap_or(4)
        .clamp(2, 64);
    match tokio::runtime::Builder::new_multi_thread()
        .worker_threads(worker_threads)
        .max_blocking_threads(8)
        .enable_all()
        .build()
    {
        Ok(rt) => {
            tauri::async_runtime::set(rt.handle().clone());
            std::mem::forget(rt);
            eprintln!("[BOOT] 下载运行时已注入: worker_threads={}, max_blocking_threads=8", worker_threads);
        }
        Err(e) => eprintln!("[BOOT] 创建自定义 tokio runtime 失败, 回退 Tauri 默认: {}", e),
    }

    eprintln!("[BOOT] VortexDL 启动, 版本={}, 操作系统={}, 架构={}", env!("CARGO_PKG_VERSION"), std::env::consts::OS, std::env::consts::ARCH);
    eprintln!("[BOOT] 进程 PID={}, 线程ID={:?}", std::process::id(), std::thread::current().id());
    eprintln!("[BOOT] exe 路径: {}", std::env::current_exe().unwrap_or_default().display());
    eprintln!("[BOOT] 工作目录: {}", std::env::current_dir().unwrap_or_default().display());
    eprintln!("[BOOT] 系统内存: {} MB, CPU 核心数: {}", get_system_memory_mb(), num_cpus());
    eprintln!("[BOOT] 用户目录: {}", std::env::var("USERPROFILE").unwrap_or_else(|_| std::env::var("HOME").unwrap_or_default()));
    eprintln!("[BOOT] 临时目录: {}", std::env::temp_dir().display());
    eprintln!("[BOOT] 命令行参数: {:?}", std::env::args().collect::<Vec<_>>());
    eprintln!("[BOOT] 环境变量 RUST_LOG: {}", std::env::var("RUST_LOG").unwrap_or_default());
    // 磁盘可用空间 (exe 所在盘)
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            eprintln!("[BOOT] exe 目录: {}", exe_dir.display());
            // 列出 logs 目录现有日志文件大小
            if let Ok(entries) = std::fs::read_dir(exe_dir.join("logs")) {
                let mut logs_info = Vec::new();
                for entry in entries.flatten() {
                    if let Ok(meta) = entry.metadata() {
                        if let Some(name) = entry.file_name().to_str() {
                            logs_info.push(format!("{}={}KB", name, meta.len() / 1024));
                        }
                    }
                }
                eprintln!("[BOOT] 现有日志文件: {}", logs_info.join(", "));
            }
        }
    }

    crate::boot_helpers::print_frontend_fingerprint();

    // ★ 日志增强 (2026-09-15): 写入 system.log 初始快照, 记录启动时系统状态
    app_logger::log_system("BOOT", &format!(
        "version={} pid={} os={} arch={} sys_mem_mb={} app_rss_mb={} cpu_cores={}",
        env!("CARGO_PKG_VERSION"), std::process::id(),
        std::env::consts::OS, std::env::consts::ARCH,
        get_system_memory_mb(), get_app_rss_mb(), num_cpus()
    ));
    app_logger::log_config("LOAD", "应用启动, 加载配置");

    tauri::Builder::default()
        .manage(AppState::new())
        .setup(|app| {
            crate::licensing::start_watchdog(app.handle().clone());
            // ★ GX（galgamex 游戏库）索引：启动时把磁盘索引读进内存，
            //   前端一进页面就能直接浏览，不用等同步。
            crate::gx::load_index_from_disk();
            // ★★ 索引为空 → 后台自动同步一次（2026-10-08）。
            //
            //   装到干净机器上时 `data/gx/index.json` 可能不存在（安装包不一定带），
            //   成人页的 GX 段（55%）就永远是空的 —— 用户报「安装包里成人游戏
            //   没资源就只有两个」正是这个（只剩 BY 那 5% 的两条）。
            //   这里在后台悄悄拉一次，不阻塞启动。
            if crate::gx::total_cards() == 0 && crate::licensing::is_activated() {
                let handle = app.handle().clone();
                let handle2 = handle.clone();
                tauri::async_runtime::spawn(async move {
                    let log = move |m: &str| {
                        let _ = handle2.emit("gx-sync-progress", serde_json::json!({ "message": m }));
                    };
                    match crate::gx::sync(&log).await {
                        Ok(idx) => {
                            crate::app_logger::log_system(
                                "GX_AUTO_SYNC",
                                &format!("首次启动自动同步完成, {} 个游戏", idx.cards.len()),
                            );
                            let _ = handle.emit("gx-sync-progress", serde_json::json!({ "message": "done" }));
                        }
                        Err(e) => crate::app_logger::log_system(
                            "GX_AUTO_SYNC",
                            &format!("自动同步失败（成人页 GX 段会为空）: {e}"),
                        ),
                    }
                });
            }
            // ★ 读取配置, 初始化后台下载开关
            let config = crate::config::Config::load();
            BACKGROUND_DOWNLOAD.store(config.background_download, Ordering::Relaxed);

            // ★ 系统托盘: 后台静默下载的核心
            //   - 左键点击托盘图标: 显示并聚焦主窗口
            //   - 右键菜单: "显示窗口" / "退出"
            //   - 窗口关闭按钮: 隐藏到托盘而非退出进程, 下载继续在后台运行
            let show_item = MenuItem::with_id(app, "show", "显示窗口", true, None::<&str>)?;
            let quit_item = MenuItem::with_id(app, "quit", "退出 VortexDL", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&show_item, &quit_item])?;

            let _tray = TrayIconBuilder::new()
                .icon(app.default_window_icon().unwrap().clone())
                .menu(&menu)
                .tooltip("VortexDL 漩涡下载器 (后台运行中)")
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        app_logger::log_window("TRAY_CLICK", "左键点击托盘图标, 显示窗口");
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                })
                .on_menu_event(|app, event| {
                    match event.id.as_ref() {
                        "show" => {
                            app_logger::log_window("MENU_SHOW", "托盘菜单: 显示窗口");
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.show();
                                let _ = window.set_focus();
                            }
                        }
                        "quit" => {
                            app_logger::log_window("MENU_QUIT", "托盘菜单: 退出 VortexDL");
                            app.exit(0);
                        }
                        _ => {}
                    }
                })
                .build(app)?;

            // ★ 白屏兜底 (2026-10-03): 窗口以 visible:false 启动, 由前端 init 完成后
            //   调用 show_main_window 显示。若前端因任何原因没调 (崩溃/JS 异常),
            //   这里 3 秒后强制显示, 避免用户"启动了但什么都没有"。
            {
                let app_fb = app.handle().clone();
                tauri::async_runtime::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    if let Some(w) = app_fb.get_webview_window("main") {
                        if !w.is_visible().unwrap_or(true) {
                            let _ = w.show();
                            let _ = w.set_focus();
                            app_logger::log_window("SHOW_FALLBACK", "前端 3 秒内未就绪, 强制显示窗口");
                        }
                    }
                });
            }

            // ★ 启动优化 (2026-09-13): 后台线程加载 16MB game_index.json, 不阻塞主线程 → 窗口秒开
            //   load_disk_index_background 是同步函数, 放在 std::thread::spawn 中执行
            let search_for_disk = app.handle().state::<AppState>().search.clone();
            std::thread::spawn(move || {
                search_for_disk.load_disk_index_background();
            });

            // ★ 后台批量翻译游戏名: 启动 15 秒后开始 (2026-09-13 优化: 5s→15s, 避开启动高峰)
            //   逐步翻译所有未翻译的游戏名, 翻译结果保存到 game_index.json
            let search = app.handle().state::<AppState>().search.clone();
            let translator = app.handle().state::<AppState>().game_translator.clone();
            tauri::async_runtime::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(15)).await;
                let mut total_translated = 0usize;
                let mut no_progress = 0u32; // 连续无进展批次数 (引擎软失败: 返回 Ok 但翻译全空)
                crate::app_logger::log_translate("BATCH_START", "后台批量翻译任务启动");
                loop {
                    let untranslated = search.get_untranslated_games();
                    if untranslated.is_empty() {
                        crate::app_logger::log_translate("BATCH_DONE", &format!("全部翻译完成, 共 {} 个", total_translated));
                        break;
                    }
                    // ★ 防死循环: 连续 5 批无任何新翻译 (引擎持续软失败) → 放弃本轮,
                    //   否则 untranslated 永不被消费, 每 1.5s 空转一次并可能反复写盘
                    if no_progress >= 5 {
                        eprintln!("[batch_translate] 连续 {no_progress} 批无进展, 翻译引擎不可用, 本轮终止 (待翻译剩余 {})", untranslated.len());
                        crate::app_logger::log_translate("BATCH_ABORT", &format!(
                            "连续 {} 批无进展, 翻译引擎不可用, 待翻译剩余 {}", no_progress, untranslated.len()
                        ));
                        break;
                    }
                    // 每批 50 个, 避免翻译 API 限流
                    let batch: Vec<(String, String)> = untranslated.into_iter().take(50).collect();
                    let names: Vec<String> = batch.iter().map(|(_, n)| n.clone()).collect();
                    match translator.translate_batch(names).await {
                        Ok(translated) => {
                            let pairs: Vec<(String, String)> = batch.iter()
                                .zip(translated.iter())
                                .filter(|((_, orig), tr)| !tr.is_empty() && tr.as_str() != orig.as_str())
                                .map(|((id, _), tr)| (id.clone(), tr.clone()))
                                .collect();
                            let n = search.batch_update_translated_names(&pairs);
                            if n == 0 { no_progress += 1; } else { no_progress = 0; }
                            total_translated += n;
                            crate::app_logger::log_translate("BATCH_PROGRESS",
                                &format!("batch_in={} translated={} total={} no_progress={}", batch.len(), n, total_translated, no_progress));
                            // ★ 性能: 每 300 个才写盘一次 (全量序列化 ~15MB + fsync 较重,
                            //   之前每批 (1.5s 一次) 都写导致启动期间持续 CPU/IO 高占用、界面卡顿)
                            if total_translated > 0 && total_translated % 300 == 0 {
                                search.save_index_to_disk();
                                eprintln!("[batch_translate] 已翻译 {} 个游戏名", total_translated);
                            }
                        }
                        Err(e) => {
                            no_progress += 1;
                            crate::app_logger::log_translate("BATCH_ERROR",
                                &format!("error={} no_progress={}", e, no_progress));
                            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                        }
                    }
                    // 每批间隔 1.5s, 避免 MyMemory 429 限流 (匿名额度有限)
                    tokio::time::sleep(std::time::Duration::from_millis(1500)).await;
                }
                search.save_index_to_disk();
                eprintln!("[batch_translate] 完成, 共翻译 {} 个游戏名", total_translated);
            });

            // ★ 日志增强 (2026-09-15): 定期记录系统资源状态到 system.log
            //   每 60 秒采样一次: 内存/CPU 核心/活跃任务数, 方便排查长时间运行后的资源泄漏
            let app_handle_snapshot = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                // ★ 内存/性能优化 (2026-09-28):
                //   (1) 复用同一个 System 实例 —— 旧实现每 60s 调 get_system_memory_mb() 会
                //       System::new_all() 全量枚举系统进程 + 刷新 CPU, 造成周期性 CPU/内存抖动;
                //   (2) 新增 app_rss_mb = 本进程常驻内存, 用于验证「下载时 <150MB」目标
                //       (旧 memory_mb 实为系统总内存的 KB 值, 无法反映本进程占用)。
                let mut sys = sysinfo::System::new();
                let my_pid = sysinfo::get_current_pid().ok();
                loop {
                    tokio::time::sleep(std::time::Duration::from_secs(60)).await;
                    sys.refresh_memory();
                    let sys_mem_mb = sys.total_memory() / 1024 / 1024;
                    let app_rss_mb = match my_pid {
                        Some(pid) => {
                            sys.refresh_process(pid);
                            sys.process(pid).map(|p| p.memory() / 1024 / 1024).unwrap_or(0)
                        }
                        None => 0,
                    };
                    let cpu = num_cpus();
                    // 统计活跃下载任务数
                    let active = app_handle_snapshot.state::<AppState>()
                        .download_tasks.lock().await.len();
                    crate::app_logger::log_system("PERIODIC", &format!(
                        "app_rss_mb={} sys_mem_mb={} cpu_cores={} active_tasks={} bg_download={}",
                        app_rss_mb, sys_mem_mb, cpu, active,
                        BACKGROUND_DOWNLOAD.load(Ordering::Relaxed)
                    ));
                }
            });

            Ok(())
        })
        .on_window_event(|window, event| {
            // ★ 后台静默下载: 关闭窗口时隐藏到托盘而非退出进程
            //   下载任务在后台继续运行, 用户可通过托盘图标重新打开窗口
            // ★ 只对**主窗口**做"关到托盘"：独立播放窗口要能正常关掉，
            //   否则用户点了 X 它只是藏起来，既看不见又关不掉。
            if window.label() == "main" && BACKGROUND_DOWNLOAD.load(Ordering::Relaxed) {
                if let WindowEvent::CloseRequested { api, .. } = event {
                    crate::app_logger::log_window("CLOSE_HIDE", "关闭按钮 → 隐藏到托盘 (后台下载继续)");
                    let _ = window.hide();
                    api.prevent_close();
                }
            }
            // ★ 日志增强 (2026-09-15): 记录窗口事件到 window.log
            match event {
                WindowEvent::CloseRequested { .. } => {
                    crate::app_logger::log_window("CLOSE_REQ", "窗口关闭请求");
                }
                WindowEvent::Focused(f) => {
                    crate::app_logger::log_window("FOCUS", &format!("focused={}", f));
                }
                WindowEvent::ScaleFactorChanged { .. } => {
                    crate::app_logger::log_window("SCALE", "缩放比例变化");
                }
                _ => {}
            }
        })
        .invoke_handler(tauri::generate_handler![
            get_config, save_config,
            show_main_window,
    license_status, license_activate,
            browse, browse_by_category, get_adult_tags, browse_adult, search_adult, adult_browse_local, adult_categories, adult_total, search, fetch_detail, fetch_downloads,
            translate, translate_game_info, set_translate_lang, get_translate_lang, clear_translate_cache, translate_force,
            game_tr_set_engine, game_tr_get_engine, game_tr_set_config, game_tr_get_config,
            game_tr_translate, game_tr_translate_batch, game_tr_translate_dir, game_tr_clear_cache,
            save_translated_name, save_translated_names, translate_all_game_names,
            start_download, cancel_download, pause_download, resume_download, retry_download, get_downloads_status,
            parse_torrent_preview,
            get_speed_engine_status, aria2_status, aria2_start, aria2_stop, aria2_get_active_downloads,
            clear_cache, snapshot_stats, snapshot_categories, refresh_snapshot, preload_byko, clear_snapshot, reset_adult_tags, recommend,
            get_cache_usage, clear_temp_cache, clear_app_cache,
            vx_window_min, vx_window_toggle_max, vx_window_close,
            anime_home, anime_detail, anime_search_bgm,
            anime_follow, anime_follow_toggle, anime_follow_progress, anime_danmaku,
            anime_sources, anime_search_online, anime_search_all, anime_episodes, anime_resolve,
            anime_hot, anime_rec_paged,
            open_folder, open_file, delete_path, launch_program, program_exists, extract_archive, list_archives, check_bt_disk_progress, browse_path, get_game_translator_path,
            copy_to_clipboard,
            get_app_info, mark_version_seen, check_app_update, download_app_update,
            get_system_status, append_frontend_log,
            open_external_browser,
            game_scrape_site, game_scrape_pick_download,
            gx_sync, gx_status, gx_tags, gx_browse, gx_detail, gx_resources, gx_pick_download, gx_related,
            open_player_window, player_take_payload, focus_main_and_open, raise_main_window, main_sync_subject,
            create_desktop_shortcut, list_exe_candidates,
            repair_runtime,
            restart_system,
            // —— 修改器 ——
            tr_sync, tr_index, tr_detail, tr_download, tr_library,
            tr_import, tr_delete, tr_launch, tr_rename, tr_translate_names, tr_open_folder,
            tr_defender_exclude,
            // —— 书库 ——
            book_home, book_search, book_content, book_download, book_extra_downloads,
            book_local_dir, book_open_local_dir, book_import, book_probe, book_translate,
        ])
        .run(tauri::generate_context!())
        .expect("error while running vortex-dl application");
}